{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "program-director.fullname" . }}-config
  labels:
    {{- include "program-director.labels" . | nindent 4 }}
type: Opaque
stringData:
  radarr-api-key: {{ .Values.config.radarr.apiKey | quote }}
  sonarr-api-key: {{ .Values.config.sonarr.apiKey | quote }}
  {{- if .Values.config.trakt.clientId }}
  trakt-client-id: {{ .Values.config.trakt.clientId | quote }}
  {{- end }}
  {{- if .Values.config.trakt.clientSecret }}
  trakt-client-secret: {{ .Values.config.trakt.clientSecret | quote }}
  {{- end }}
  {{- if eq .Values.config.database.driver "postgres" }}
  postgres-password: {{ .Values.config.database.postgres.password | quote }}
  {{- end }}
{{- end }}
